language: go
go:
  - 1.4.2
  - 1.4.1
  - 1.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3
  - release
  - tip
env:
  - DB=sqlite3
  - DB=mysql
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS argen_tests'; fi"
script:
  - go test -v ./...
